//
//  Projects.swift
//  Showcase
//
//  Created by Carlos Cabral on 23/11/21.
//

import SwiftUI

struct Project: Identifiable {
    let id = UUID()
    let logoName: String
    let imageName: String
    let title: String
    let description: String
    let color: Color
}

struct Projects {
    
    static let startupProjects = [
        Project(logoName: "ben4you-logo", imageName: "img-ben4you", title: "Ben4You", description: "Have a dreams, pane, and not matters sign waved said sister are and he like have get spots my put you stash what attempt. With and all the and aside, with in he illustrated gilded enough semantics, needed legs, design rome; River and for to helped far high deference it happiness in mouse the client occasion volume have the and one as of negotiations quite picture recently bathroom avarice were dissolute these was even it to eminent the and was may he the their there, its town to of great by and it that of the or makers of avoid. And everyone odd more learn pitifully heard people left with separated my it concepts design associate felt earnestly the choose at out moving mad word steps. The a tone great. The if on. Presented be is our because military venerable, on based wanted by with during avoided onto dresses until is back room. Didn't and could found it continues best the and day this harder competitive thought, the far and tone our with lowest read. Frequencies should and by on had in bit more differentiates is universal had differences tried as good for seven could heavily of my disguised travelling.", color: .red),
        Project(logoName: "pdal-logo", imageName: "img-pdal", title: "Pdal", description: "Have a dreams, pane, and not matters sign waved said sister are and he like have get spots my put you stash what attempt. With and all the and aside, with in he illustrated gilded enough semantics, needed legs, design rome; River and for to helped far high deference it happiness in mouse the client occasion volume have the and one as of negotiations quite picture recently bathroom avarice were dissolute these was even it to eminent the and was may he the their there, its town to of great by and it that of the or makers of avoid. And everyone odd more learn pitifully heard people left with separated my it concepts design associate felt earnestly the choose at out moving mad word steps. The a tone great. The if on. Presented be is our because military venerable, on based wanted by with during avoided onto dresses until is back room. Didn't and could found it continues best the and day this harder competitive thought, the far and tone our with lowest read. Frequencies should and by on had in bit more differentiates is universal had differences tried as good for seven could heavily of my disguised travelling.", color: .green),
        Project(logoName: "resorts-logo", imageName: "img-resorts", title: "Resorts", description: "Have a dreams, pane, and not matters sign waved said sister are and he like have get spots my put you stash what attempt. With and all the and aside, with in he illustrated gilded enough semantics, needed legs, design rome; River and for to helped far high deference it happiness in mouse the client occasion volume have the and one as of negotiations quite picture recently bathroom avarice were dissolute these was even it to eminent the and was may he the their there, its town to of great by and it that of the or makers of avoid. And everyone odd more learn pitifully heard people left with separated my it concepts design associate felt earnestly the choose at out moving mad word steps. The a tone great. The if on. Presented be is our because military venerable, on based wanted by with during avoided onto dresses until is back room. Didn't and could found it continues best the and day this harder competitive thought, the far and tone our with lowest read. Frequencies should and by on had in bit more differentiates is universal had differences tried as good for seven could heavily of my disguised travelling.", color: .yellow)

    ]
    
    static let corporateProjects = [
        Project(logoName: "oxiteno-logo", imageName: "img-oxiteno", title: "Oxiteno", description: "Have a dreams, pane, and not matters sign waved said sister are and he like have get spots my put you stash what attempt. With and all the and aside, with in he illustrated gilded enough semantics, needed legs, design rome; River and for to helped far high deference it happiness in mouse the client occasion volume have the and one as of negotiations quite picture recently bathroom avarice were dissolute these was even it to eminent the and was may he the their there, its town to of great by and it that of the or makers of avoid. And everyone odd more learn pitifully heard people left with separated my it concepts design associate felt earnestly the choose at out moving mad word steps. The a tone great. The if on. Presented be is our because military venerable, on based wanted by with during avoided onto dresses until is back room. Didn't and could found it continues best the and day this harder competitive thought, the far and tone our with lowest read. Frequencies should and by on had in bit more differentiates is universal had differences tried as good for seven could heavily of my disguised travelling.", color: .blue),
        Project(logoName: "sanofi-logo", imageName: "img-sanofi", title: "Sanofi", description: "Have a dreams, pane, and not matters sign waved said sister are and he like have get spots my put you stash what attempt. With and all the and aside, with in he illustrated gilded enough semantics, needed legs, design rome; River and for to helped far high deference it happiness in mouse the client occasion volume have the and one as of negotiations quite picture recently bathroom avarice were dissolute these was even it to eminent the and was may he the their there, its town to of great by and it that of the or makers of avoid. And everyone odd more learn pitifully heard people left with separated my it concepts design associate felt earnestly the choose at out moving mad word steps. The a tone great. The if on. Presented be is our because military venerable, on based wanted by with during avoided onto dresses until is back room. Didn't and could found it continues best the and day this harder competitive thought, the far and tone our with lowest read. Frequencies should and by on had in bit more differentiates is universal had differences tried as good for seven could heavily of my disguised travelling.", color: .purple),
        Project(logoName: "claro-logo", imageName: "img-claro", title: "Claro", description: "Have a dreams, pane, and not matters sign waved said sister are and he like have get spots my put you stash what attempt. With and all the and aside, with in he illustrated gilded enough semantics, needed legs, design rome; River and for to helped far high deference it happiness in mouse the client occasion volume have the and one as of negotiations quite picture recently bathroom avarice were dissolute these was even it to eminent the and was may he the their there, its town to of great by and it that of the or makers of avoid. And everyone odd more learn pitifully heard people left with separated my it concepts design associate felt earnestly the choose at out moving mad word steps. The a tone great. The if on. Presented be is our because military venerable, on based wanted by with during avoided onto dresses until is back room. Didn't and could found it continues best the and day this harder competitive thought, the far and tone our with lowest read. Frequencies should and by on had in bit more differentiates is universal had differences tried as good for seven could heavily of my disguised travelling.", color: .purple)
    ]

}
