//
//  Projects.swift
//  Showcase
//
//  Created by Carlos Cabral on 23/11/21.
//

import SwiftUI

struct Project: Identifiable {
    let id = UUID()
    let logoName: String
    let imageName: String
    let title: String
    let description: String
    let technologies: [String]
    let projectName: String
    let secondImage: String
}

struct Projects {
    
    static let startupProjects = [
        Project(logoName: "ben4you-logo", imageName: "img-ben4you", title: "Ben4You", description: "Noel Thomas David Gallagher (born 29 May 1967) is an English singer, songwriter, and musician as he served as the songwriter, lead guitarist, and co-lead vocalist of the rock band Oasis. After leaving Oasis in 2009, he formed and became the lead vocalist, guitarist, and songwriter for Noel Gallagher's High Flying Birds. Oasis had various line-up changes, though Gallagher and his brother Liam remained as the staple members. Gallagher began playing guitar at the age of 12, and became a roadie and technician for Inspiral Carpets at the age of 21. He learned that Liam had formed a band called The Rain, which eventually became Oasis, and Liam invited him to join them as the lead guitarist. He agreed on condition that he would write their material. The band's debut album, Definitely Maybe (1994), was a critical and commercial success. Their second album, (What's the Story) Morning Glory? (1995), reached the top of the album charts in many countries, and their third studio album, Be Here Now (1997), became the fastest-selling album in UK chart history. Britpop eventually declined in popularity and Oasis failed to revive it, though their final two albums, Don't Believe the Truth (2005) and Dig Out Your Soul (2008), were hailed as their best efforts in over a decade. In August 2009, following an altercation with Liam, Noel announced his departure from Oasis.[1] Gallagher would go on to form Noel Gallagher's High Flying Birds, with whom he has released three studio albums.", technologies: ["web", "mobile"], projectName: "Ben4you", secondImage: "img-ben4you-2"),
        Project(logoName: "pdal-logo", imageName: "img-pdal", title: "Pdal", description: "Noel Thomas David Gallagher (born 29 May 1967) is an English singer, songwriter, and musician as he served as the songwriter, lead guitarist, and co-lead vocalist of the rock band Oasis. After leaving Oasis in 2009, he formed and became the lead vocalist, guitarist, and songwriter for Noel Gallagher's High Flying Birds. Oasis had various line-up changes, though Gallagher and his brother Liam remained as the staple members. Gallagher began playing guitar at the age of 12, and became a roadie and technician for Inspiral Carpets at the age of 21. He learned that Liam had formed a band called The Rain, which eventually became Oasis, and Liam invited him to join them as the lead guitarist. He agreed on condition that he would write their material. The band's debut album, Definitely Maybe (1994), was a critical and commercial success. Their second album, (What's the Story) Morning Glory? (1995), reached the top of the album charts in many countries, and their third studio album, Be Here Now (1997), became the fastest-selling album in UK chart history. Britpop eventually declined in popularity and Oasis failed to revive it, though their final two albums, Don't Believe the Truth (2005) and Dig Out Your Soul (2008), were hailed as their best efforts in over a decade. In August 2009, following an altercation with Liam, Noel announced his departure from Oasis.[1] Gallagher would go on to form Noel Gallagher's High Flying Birds, with whom he has released three studio albums.", technologies: ["web", "mobile"], projectName: "Pdal", secondImage: "img-pdal-2"),
        Project(logoName: "resorts-logo", imageName: "img-resorts", title: "Resorts", description: "Noel Thomas David Gallagher (born 29 May 1967) is an English singer, songwriter, and musician as he served as the songwriter, lead guitarist, and co-lead vocalist of the rock band Oasis. After leaving Oasis in 2009, he formed and became the lead vocalist, guitarist, and songwriter for Noel Gallagher's High Flying Birds. Oasis had various line-up changes, though Gallagher and his brother Liam remained as the staple members. Gallagher began playing guitar at the age of 12, and became a roadie and technician for Inspiral Carpets at the age of 21. He learned that Liam had formed a band called The Rain, which eventually became Oasis, and Liam invited him to join them as the lead guitarist. He agreed on condition that he would write their material. The band's debut album, Definitely Maybe (1994), was a critical and commercial success. Their second album, (What's the Story) Morning Glory? (1995), reached the top of the album charts in many countries, and their third studio album, Be Here Now (1997), became the fastest-selling album in UK chart history. Britpop eventually declined in popularity and Oasis failed to revive it, though their final two albums, Don't Believe the Truth (2005) and Dig Out Your Soul (2008), were hailed as their best efforts in over a decade. In August 2009, following an altercation with Liam, Noel announced his departure from Oasis.[1] Gallagher would go on to form Noel Gallagher's High Flying Birds, with whom he has released three studio albums.", technologies: ["web", "mobile"], projectName: "Resorts", secondImage: "img-resorts-2")

    ]
    
    static let corporateProjects = [
        Project(logoName: "ambev-logo", imageName: "img-ambev", title: "Ambev", description: "Noel Thomas David Gallagher (born 29 May 1967) is an English singer, songwriter, and musician as he served as the songwriter, lead guitarist, and co-lead vocalist of the rock band Oasis. After leaving Oasis in 2009, he formed and became the lead vocalist, guitarist, and songwriter for Noel Gallagher's High Flying Birds. Oasis had various line-up changes, though Gallagher and his brother Liam remained as the staple members. Gallagher began playing guitar at the age of 12, and became a roadie and technician for Inspiral Carpets at the age of 21. He learned that Liam had formed a band called The Rain, which eventually became Oasis, and Liam invited him to join them as the lead guitarist. He agreed on condition that he would write their material. The band's debut album, Definitely Maybe (1994), was a critical and commercial success. Their second album, (What's the Story) Morning Glory? (1995), reached the top of the album charts in many countries, and their third studio album, Be Here Now (1997), became the fastest-selling album in UK chart history. Britpop eventually declined in popularity and Oasis failed to revive it, though their final two albums, Don't Believe the Truth (2005) and Dig Out Your Soul (2008), were hailed as their best efforts in over a decade. In August 2009, following an altercation with Liam, Noel announced his departure from Oasis.[1] Gallagher would go on to form Noel Gallagher's High Flying Birds, with whom he has released three studio albums.", technologies: ["web"], projectName: "Comitê de Gente", secondImage: "img-ambev-2"),
        Project(logoName: "oxiteno-logo", imageName: "img-oxiteno", title: "Oxiteno", description: "Noel Thomas David Gallagher (born 29 May 1967) is an English singer, songwriter, and musician as he served as the songwriter, lead guitarist, and co-lead vocalist of the rock band Oasis. After leaving Oasis in 2009, he formed and became the lead vocalist, guitarist, and songwriter for Noel Gallagher's High Flying Birds. Oasis had various line-up changes, though Gallagher and his brother Liam remained as the staple members. Gallagher began playing guitar at the age of 12, and became a roadie and technician for Inspiral Carpets at the age of 21. He learned that Liam had formed a band called The Rain, which eventually became Oasis, and Liam invited him to join them as the lead guitarist. He agreed on condition that he would write their material. The band's debut album, Definitely Maybe (1994), was a critical and commercial success. Their second album, (What's the Story) Morning Glory? (1995), reached the top of the album charts in many countries, and their third studio album, Be Here Now (1997), became the fastest-selling album in UK chart history. Britpop eventually declined in popularity and Oasis failed to revive it, though their final two albums, Don't Believe the Truth (2005) and Dig Out Your Soul (2008), were hailed as their best efforts in over a decade. In August 2009, following an altercation with Liam, Noel announced his departure from Oasis.[1] Gallagher would go on to form Noel Gallagher's High Flying Birds, with whom he has released three studio albums.", technologies: ["web", "mobile"], projectName: "Oxiteno Solutions", secondImage: "img-oxiteno-2"),
        Project(logoName: "sanofi-logo", imageName: "img-sanofi", title: "Sanofi", description: "Noel Thomas David Gallagher (born 29 May 1967) is an English singer, songwriter, and musician as he served as the songwriter, lead guitarist, and co-lead vocalist of the rock band Oasis. After leaving Oasis in 2009, he formed and became the lead vocalist, guitarist, and songwriter for Noel Gallagher's High Flying Birds. Oasis had various line-up changes, though Gallagher and his brother Liam remained as the staple members. Gallagher began playing guitar at the age of 12, and became a roadie and technician for Inspiral Carpets at the age of 21. He learned that Liam had formed a band called The Rain, which eventually became Oasis, and Liam invited him to join them as the lead guitarist. He agreed on condition that he would write their material. The band's debut album, Definitely Maybe (1994), was a critical and commercial success. Their second album, (What's the Story) Morning Glory? (1995), reached the top of the album charts in many countries, and their third studio album, Be Here Now (1997), became the fastest-selling album in UK chart history. Britpop eventually declined in popularity and Oasis failed to revive it, though their final two albums, Don't Believe the Truth (2005) and Dig Out Your Soul (2008), were hailed as their best efforts in over a decade. In August 2009, following an altercation with Liam, Noel announced his departure from Oasis.[1] Gallagher would go on to form Noel Gallagher's High Flying Birds, with whom he has released three studio albums.", technologies: ["web", "mobile"], projectName: "Direto ao Ponto", secondImage: "img-sanofi-2"),
        Project(logoName: "claro-logo", imageName: "img-claro", title: "Claro", description: "Noel Thomas David Gallagher (born 29 May 1967) is an English singer, songwriter, and musician as he served as the songwriter, lead guitarist, and co-lead vocalist of the rock band Oasis. After leaving Oasis in 2009, he formed and became the lead vocalist, guitarist, and songwriter for Noel Gallagher's High Flying Birds. Oasis had various line-up changes, though Gallagher and his brother Liam remained as the staple members. Gallagher began playing guitar at the age of 12, and became a roadie and technician for Inspiral Carpets at the age of 21. He learned that Liam had formed a band called The Rain, which eventually became Oasis, and Liam invited him to join them as the lead guitarist. He agreed on condition that he would write their material. The band's debut album, Definitely Maybe (1994), was a critical and commercial success. Their second album, (What's the Story) Morning Glory? (1995), reached the top of the album charts in many countries, and their third studio album, Be Here Now (1997), became the fastest-selling album in UK chart history. Britpop eventually declined in popularity and Oasis failed to revive it, though their final two albums, Don't Believe the Truth (2005) and Dig Out Your Soul (2008), were hailed as their best efforts in over a decade. In August 2009, following an altercation with Liam, Noel announced his departure from Oasis.[1] Gallagher would go on to form Noel Gallagher's High Flying Birds, with whom he has released three studio albums.", technologies: ["mobile"], projectName: "Claro 9º Dígito", secondImage: "img-claro-2")
    ]

}
