//
//  Projects.swift
//  Showcase
//
//  Created by Carlos Cabral on 23/11/21.
//

import SwiftUI

struct Project: Identifiable {
    let id = UUID()
    let logoName: String
    let imageName: String
    let title: String
    let description: String
    let technologies: [String]
    let projectName: String
    let secondImage: String
}

struct Projects {
    
    static let startupProjects = [
        Project(logoName: "ben4you-logo", imageName: "img-ben4you", title: "Ben4You", description: "O **Ben4You** é um aplicativo disponível para web e mobile que te apresenta descontos e benefícios que você nem sabia que existiam! Ele te informa sobre vantagens em estabelecimentos como hotéis, restaurantes, cinemas, lojas, teatros, estacionamentos, empresas de seguro e muito mais. O cliente procurou a Abacomm com um MVP simplificado da ferramenta em mãos e com a demanda de refazer o layout para algo que fosse muito mais intuitivo e que chamasse a atenção do público alvo, além de adicionar novas features e reescrever a lógica por trás das funcionalidades principais.\n\nA Abacomm embarcou no desafio e, além da parte tecnológica, propôs uma reescrita completa da identidade visual, atraindo novos públicos e alcançando o ROI esperado pelo cliente! Recentemente, o Ben4You foi citado em uma Newsletter de grande circulação e recomendado como um excelente produto para o consumidor final.", technologies: ["web", "mobile"], projectName: "Ben4you", secondImage: "img-ben4you-2"),
        Project(logoName: "pdal-logo", imageName: "img-pdal", title: "Pdal", description: "Você está em busca de aulas de bike indoor orientadas por profissionais de alta qualidade e referência do mercado? Foi a partir desse briefing que mergulhamos de cabeça nesse desafio de conceber uma plataforma de streaming para disponibilização e comercialização de audio classes voltadas para a prática de indoor cycling. O **Pdal** consiste em um aplicativo para iPhone e Android onde o atleta cria a sua conta de usuário, navega entre os melhores professores, seleciona o tipo de treino desejado e escolhe uma das aulas disponíveis na plataforma para iniciar seu percurso. E tudo isso, claro, com muita música boa ao fundo, selecionadas à dedo pelos professores.\n\nO projeto também conta com um portal web administrativo, por onde os responsáveis pela plataforma cadastram novos professores, tipos de treinos e fazem o upload dos arquivos de áudio.", technologies: ["web", "mobile"], projectName: "Pdal", secondImage: "img-pdal-2"),
        Project(logoName: "resorts-logo", imageName: "img-resorts", title: "Resorts", description: "Imagine estar hospedado em um resort e ter um aplicativo onde praticantes de Skiing e Snowboarding possam planejar suas atividades e receber instruções por voz - em tempo real - sobre localização de pistas, lifts e uma série de outras coisas inerentes à atividade! E tudo isso, mesmo que o smartphone esteja offline… Pois é, o aplicativo **Resorts** está sendo desenvolvido pela Abacomm e logo estará disponível para iOS e Android. Através de uma interface simples e intuitiva, o usuário pode traçar sua rota baseada nos lifts de sua escolha. Mas a melhor parte do aplicativo é, sem dúvidas, a experiência guiada. Uma vez que você inicia o trajeto, uma voz amigável vai te guiando durante todo o percurso, independente da sua experiência profissional e você ainda será avisado sobre pontos de interesse próximos à você.\n\nO aplicativo **Resorts** ainda conta com um track de performance, que te dá informações como recordes de velocidade e altitude e você ainda pode compartilhar todas essas conquistas nas redes sociais!", technologies: ["web", "mobile"], projectName: "Resorts", secondImage: "img-resorts-2")

    ]
    
    static let corporateProjects = [
        Project(logoName: "ambev-logo", imageName: "img-ambev", title: "Ambev", description: "A Abacomm foi procurada pela Ambev para dar vida à um projeto chamado **Comitê de Melhores Práticas**, com o objetivo de oferecer total transparência e  incentivar uma dedicação contínua entre todas as equipes participantes do comitê, através de uma experiência única e exclusiva dentro do grupo Ambev. Pela plataforma é possível ter visão, em tempo real, do status de todas as melhores  práticas acordadas pelo comitê em cada uma das unidades da Ambev. Também é possível realizar comparativo entre diferentes unidades e regiões, além de acesso a uma timeline informativa onde os membros poderão postar novidades sobre suas unidades.\n\nCada post poderá ser curtido e comentado pelos outros usuários, gerando um canal de comunicação mais  informal, onde as conquistas são compartilhadas e celebradas com todos! Além disso, a plataforma oferece uma área administrativa para análise de relatórios que irão fornecer diversos insights sobre o cotidiano de cada grupo de trabalho, facilitando a observação de padrões na forma como algumas unidades atingem as metas estabelecidas, enquanto outras enfrentam dificuldades.", technologies: ["web"], projectName: "Comitê de Gente", secondImage: "img-ambev-2"),
        Project(logoName: "oxiteno-logo", imageName: "img-oxiteno", title: "Oxiteno", description: "Muitas empresas tem a necessidade de potencializar ações de marketing e apresentar os produtos da empresa de maneira atrativa, seja por meio de apresentações dos times comerciais, estandes em eventos ou grandes congressos. A multinacional Oxiteno tinha essa demanda dentro de casa e precisava de uma empresa de transformação digital para conduzir esse desafio. O resultado foi o **Oxiteno Solutions**, que consiste em um aplicativo mobile com todas as informações dos produtos da empresa separados por segmentos de mercado e com um recurso onde as pessoas em eventos podem apontar para os QRCodes e acessar informações completas destes produtos de uma forma interativa.\n\nO projeto ainda conta com um portal administrativo, por onde os responsáveis pela plataforma também podem cadastrar conteúdos adicionais, como vídeos e catálogos. O aplicativo Oxiteno Solutions está disponível nos idiomas inglês e português.", technologies: ["web", "mobile"], projectName: "Oxiteno Solutions", secondImage: "img-oxiteno-2"),
        Project(logoName: "sanofi-logo", imageName: "img-sanofi", title: "Sanofi", description: "Gerir times de forma eficaz através de ferramentas de desenvolvimento e avaliação de desempenho é uma das dores de equipes administrativas e de recursos-humanos da maioria das empresas! Não foi diferente com o grupo Sanofi, que precisava de uma ferramenta exclusiva que tivesse essas características. Foi assim que surgiu o **Direto ao Ponto**. Uma plataforma focada em melhorar a experiência das atividades de coaching entre gestores e consultores do grupo.\n\nO projeto consiste em um aplicativo para iPhone e Android que é usado para preenchimento e planejamento dos coachings, um aplicativo para iPad, onde os consultores recebem suas avaliações e fazem o acompanhamento das ações e treinamentos sugeridos e um portal web administrativo para análise de relatórios qualitativos (comparação de respostas, evoluções, etc) e quantitativo (percentual de avaliações aplicadas em cada equipe e afins).\n\nEste é um projeto que foi desenvolvido a partir de uma estrutura técnica bastante sólida e escalável, já servindo de base para todas as evoluções e experimentações que possam surgir ao longo da operação com os usuários finais.", technologies: ["web", "mobile"], projectName: "Direto ao Ponto", secondImage: "img-sanofi-2"),
        Project(logoName: "claro-logo", imageName: "img-claro", title: "Claro", description: "Há 9 anos atrás a Abacomm lançava o 9º Dígito nas lojas de aplicativos, com a premissa de ajudar o usuário à fazer a inclusão do dígito 9 à frente dos números da sua agenda de contatos, que seria obrigatório a partir de 06 de Novembro daquele mesmo ano! Mas o utilitário não se limitava apenas à isso, uma vez que o app também possibilitava organizar a agenda de telefones e padronizar a operadora de Longa Distância de preferência do usuário. O resultado foi o melhor app da sua categoria, o que nos rendeu o 1º lugar na lista de apps mais baixados da App Store com uma média de 5.0 (nota máxima) em relação à satisfação do usuário. Estivemos presentes na mídia especializada com matérias nos sites [GIZMODO](https://gizmodo.uol.com.br/9digito-para-ios-e-android-melhor-forma-de-se-preparar-para-o-digito-9/) e [MacMagazine](https://macmagazine.com.br/post/2012/07/09/9digito-e-mais-um-app-que-automatiza-a-atualizacao-de-numeros-telefonicos-em-sao-paulo/) e fomos selecionados pela revista **Info** para a seção ***Apps que valem à pena***, vinculada naquele mesmo ano.\n\nO sucesso estrondoso do 9 Dígito foi tamanho que diversas empresas procuraram a Abacomm para licenciar o uso do aplicativo e fornecer a mesma experiência positiva aos seus usuários. Como foi o caso da empresa CLARO, que, no ano de 2021, contratou o desenvolvimento de uma versão exclusiva e atualizada com novos recursos, 100% otimizada para celulares mais novos e com o objetivo principal de fidelizar seus clientes que foram migrados a partir da Nextel.", technologies: ["mobile"], projectName: "Claro Agenda", secondImage: "img-claro-2")
    ]

}
